[tokens]
DATABASE = 0
PASSWORD = "MPZYYYt767TNL0Hh4b151dKPSXmlB71KySTprpz6AAMKdefArpXCAHwa2D38ke1k4Qnm+XQyGAGG7eNaCuI2lYXWKoHM+DItznsQ9b9mop"
HOST = "rc1c-qtf1qu9fe64k3bz9.mdb.yandexcloud.net"
PORT = 6379

[monitor]
DATABASE = 1
PASSWORD = "MPZYYYt767TNL0Hh4b151dKPSXmlB71KySTprpz6AAMKdefArpXCAHwa2D38ke1k4Qnm+XQyGAGG7eNaCuI2lYXWKoHM+DItznsQ9b9mop"
HOST = "rc1c-qtf1qu9fe64k3bz9.mdb.yandexcloud.net"
PORT = 6379

[events]
DATABASE = 2
PASSWORD = "MPZYYYt767TNL0Hh4b151dKPSXmlB71KySTprpz6AAMKdefArpXCAHwa2D38ke1k4Qnm+XQyGAGG7eNaCuI2lYXWKoHM+DItznsQ9b9mop"
HOST = "rc1c-qtf1qu9fe64k3bz9.mdb.yandexcloud.net"
PORT = 6379

[data]
DATABASE = 3
PASSWORD = "MPZYYYt767TNL0Hh4b151dKPSXmlB71KySTprpz6AAMKdefArpXCAHwa2D38ke1k4Qnm+XQyGAGG7eNaCuI2lYXWKoHM+DItznsQ9b9mop"
HOST = "rc1c-qtf1qu9fe64k3bz9.mdb.yandexcloud.net"
PORT = 6379

[collections]
DATABASE = 4
PASSWORD = "MPZYYYt767TNL0Hh4b151dKPSXmlB71KySTprpz6AAMKdefArpXCAHwa2D38ke1k4Qnm+XQyGAGG7eNaCuI2lYXWKoHM+DItznsQ9b9mop"
HOST = "rc1c-qtf1qu9fe64k3bz9.mdb.yandexcloud.net"
PORT = 6379
