[API]
# Автоматические подключение сессий по вебсокету:
# "NONE" - не подключать
# "AUTH" - подключать сессии только авторизованных пользователей
# "ALL" - подключать все сессии
# Объекты подключений к вебсокету хранятся в API.websockets
WEBSOCKET = "AUTH"
# Автоматически создавать подключение к Redis
# Подключение хранится в API.redis
# Конфиг redis.toml должен сожержать подключение
REDIS = [ "tokens", "monitor", "data", "collections" ]
# Автоматически создавать подключение к каналу событий Redis
# Подключение хранится в API.redis
# Конфиг redis.toml должен сожержать подключение
MQ = [ "events" ]
# Автоматически создавать пулы подключений к PostgreSQL
# Конфиг pg.toml должен сожержать подключения [alias]
# Подключение хранится в API.pg[alias]
PG = [ "digitender" ]
# Интервал публикации состояния воркера в Redis в секундах
# Если 0, то не публиковать
ENROLL_INTERVAL = 10


[REDIS]
# Время ожидание доступности Redis для запросов в секундах
QUEUE_TIMEOUT = 3
# Время жизни запроса к Redis в секундах
COMMAND_TIMEOUT = 3
# Интервал проверки соединения с Redis в секундах
PING_INTERVAL = 15
# Интервал проверки новых сообщений в очереди сообщений в секундах
MQ_CHECK_INTERVAL = 1
# Время жизни сообщения в очереди в секундах
MQ_MESSAGE_LIFETIME = 20


[PG]
# Максимальное количество подключений к PostgreSQL на один воркер
MAX_CONNECTIONS_PER_WORKER = 3
# Количество подключений, которые не закрываются в случай неактивности
MIN_ACTIVE_CONNECTIONS_PER_WORKER = 2
# Время ожидание доступности PostgreSQL для запросов в секундах
QUEUE_TIMEOUT = 10
# Время жизни запроса к Redis в секундах
COMMAND_TIMEOUT = 20
# Максимальное время отработки транзакции в секундах
# По истечении времени транзакция автоматически откатывается и закрывается
MAX_TRANSACTION_TIME = 60
# Интервал проверки соединения с PostgreSQL в секундах
PING_INTERVAL = 30
# Время жизни неактивного подключения в секундах
INACTIVE_CONNECTION_LIFETIME = 300


[AUTH]
# Время жизни активного токена сессии в секундах
TOKEN_LIFETIME = 604800
# Время жизни отработанного токена сессии в секундах
TOKEN_DROPTIME = 600
# Логирование запросов сессий
SESSION_LOG = true
# Логирование запросов при авторизации по ключу
KEY_LOG = true
# Хэшировать пароли в базе
PASSWORD_HASHING = false
